version: '3'

services:
  toolchain:
    image: mesosphere/dcos-ui
    build:
      context: .
    environment:
       - CLUSTER_URL="${CLUSTER_URL}"
       - INSTALLER_URL="${INSTALLER_URL}"
       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 4200:4200
    volumes:
      - ./.:/dcos-ui
