version: '3'

services:
  toolchain:
    image: mesosphere/dcos-ui
    build:
      context: .
    environment:
      CLUSTER_URL: "${CLUSTER_URL}"
      INSTALLER_URL: "${INSTALLER_URL}"
      AWS_PROFILE: "${AWS_PROFILE}"
    ports:
      - 4200:4200
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./.:/dcos-ui
